server:
  port: ${PORT:9411}
spring:
#  rabbitmq:
#    host: ${RABBIT_HOST:localhost}
#  datasource:
#    schema: classpath:/mysql.sql
#    url: jdbc:mysql://${MYSQL_HOST:localhost}/zipkin
#    username: root
#    password:
# Switch this on to create the schema on startup:
#    initialize: true
#    continueOnError: true
  sleuth:
    enabled: false
zipkin:
  storage:
    type: mysql